### PR TITLE
Add custom favicon to token pages

### PR DESCRIPTION
**Pull request by laurent-h**

### CODE REVIEW

**Comment by laurent-h** [comment]
It works on chrome-based browsers and firefox. I didn't check safari.

HTML Canvas could also be used to avoid pixel glitches on the preview in some cases. Are you interested in a patch for this?

**Comment by xat** [comment]
okay, cool. think i'll just merge and check on production :)

how would that canvas solution work? you would create a 8x8 pixel canvas and then scale it?

**Comment by laurent-h** [comment]
> you would create a 8x8 pixel canvas and then scale it?

Yes (with imageRendering: 'pixelated' CSS)

**Comment by xat** [comment]
sounds great!

if it doesn't cause any problems, i'm happy to merge a canvas-based solution for the preview images :)

i'll merge this pr now. thanks!

**Comment by xat** [comment]
it's deployed. this is dope! :-)

**Comment by laurent-h** [comment]
Happy to be a contributor :-)
Second pull request with canvas preview sent.

**Pull request merged**
